name: sdp-gateway
services:
  gateway:
    image: nhatbangle/sdp-gateway:latest
    ports:
      - "8091:8080"
    environment:
      KC_SERVER_URL: localhost:8081
      KC_REALM: realm
      KC_CLIENT_ID: client-id
      KC_CLIENT_SECRET: secret

      EK_INST_ID: inst-id
      EK_INST_IPADDR: 127.0.0.1
      EK_HTTP_PORT: 8091
      SOFTWARE_SERVICE_ID: software
      FILE_SERVICE_ID: file
      NOTIFICATION_SERVICE_ID: notification