name: sdp-gateway
services:
  gateway:
    image: nhatbangle/sdp-gateway:latest
    ports:
      - "8091:8080"
    environment:
      KC_SERVER_URL: localhost:8081
      KC_REALM: realm
      KC_CLIENT_ID: client-id
      KC_CLIENT_SECRET: secret

      SOFTWARE_SERVICE_URL: http://localhost:8081
      FILE_SERVICE_URL: http://localhost:8082
      NOTIFICATION_SERVICE_URL: http://localhost:8083