spring:
  application:
    name: sdp-gateway

app:
  software-service-url: ${SOFTWARE_SERVICE_URL}
  file-service-url: ${FILE_SERVICE_URL}
  notification-service-url: ${NOTIFICATION_SERVICE_URL}
  cors-origin: ${CORS_ORIGIN:*}
  cors-methods: ${CORS_METHODS:*}

keycloak:
  server-url: ${KC_SERVER_URL}
  realm: ${KC_REALM}
  client-id: ${KC_CLIENT_ID}
  client-secret: ${KC_CLIENT_SECRET}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    urls[0]:
      name: Product Service
      url: /aggregate/product/v3/api-docs
